# Generated by Django 4.1.3 on 2022-11-17 08:20

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('application', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('answer1', models.TextField(default='', max_length=500)),
                ('answer2', models.TextField(default='', max_length=500)),
                ('answer3', models.TextField(default='', max_length=500)),
                ('answer4', models.TextField(default='', max_length=500)),
                ('answer5', models.TextField(default='', max_length=500)),
                ('answer6', models.TextField(default='', max_length=500)),
                ('applied', models.BooleanField(default=False)),
                ('Denied', models.BooleanField(default=False)),
                ('Approved', models.BooleanField(default=False)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=base.models.upload_to)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
