# Generated by Django 4.1.3 on 2022-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_application_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='applied',
            field=models.BooleanField(default=True),
        ),
    ]
