# Generated by Django 4.1.3 on 2022-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_slots_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
